version: "3.8"
services:
  frontend:
    build: frontend
    ports:
      - "3000:3000"
    volumes:
      - "./frontend:/frontend"
      - "/frontend/node_modules"
    depends_on:
      - backend
    networks:
      - matcha
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
  backend:
    build: backend
    ports:
      - "8080:8080"
      - "8888:8888"
    depends_on:
      - database
    networks:
      - matcha
  database:
    build: database
    ports:
      - "5432:5432"
    networks:
      - matcha
    stdin_open: true
  generator:
    build: generator
    ports:
      - "8000:8000"
    depends_on:
      - backend
    networks:
      - matcha
networks:
  matcha:
    driver: bridge
