version: "3.8"
services:
  frontend:
    build: frontend
    ports:
      - "3000:3000"
    volumes:
      - "./frontend:/frontend"
      - "/frontend/node_modules"
    depends_on:
      - backend
    networks:
      - matcha
    stdin_open: true
  backend:
    build: backend
    volumes:
      - "./backend:/backend"
    ports:
      - "8080:8080"
    working_dir: /backend
    command: sh run.sh
    networks:
      - matcha
networks:
  matcha:
    driver: bridge
