services:
  backend:
    build: backend
    ports:
      - "8080:8080"
    networks:
      - matcha
  db:
    build: db
    ports:
      - "5432:5432"
    networks:
      - matcha
networks:
  matcha:
    driver: bridge